#!/usr/bin/env ruby

git_bundles = [
  "http://github.com/godlygeek/tabular.git",
  "http://github.com/msanders/snipmate.vim.git",
  "http://github.com/scrooloose/nerdtree.git",
  "http://github.com/tpope/vim-fugitive.git",
  "http://github.com/tpope/vim-repeat.git",
  "http://github.com/tpope/vim-surround.git",
  "http://github.com/tsaleh/vim-align.git",
  "https://github.com/vim-scripts/LaTeX-Suite-aka-Vim-LaTeX.git"
#  "git://vim-latex.git.sourceforge.net/gitroot/vim-latex/vim-latex",
#  "http://github.com/astashov/vim-ruby-debugger.git",
#  "http://github.com/timcharper/textile.vim.git",
#  "http://github.com/tpope/vim-cucumber.git",
#  "http://github.com/tpope/vim-git.git",
#  "http://github.com/tpope/vim-haml.git",
#  "http://github.com/tpope/vim-markdown.git",
#  "http://github.com/tpope/vim-rails.git",
#  "http://github.com/tpope/vim-vividchalk.git",
#  "http://github.com/tsaleh/vim-shoulda.git",
#  "http://github.com/tsaleh/vim-tcomment.git",
#  "http://github.com/vim-ruby/vim-ruby.git",
# "http://github.com/kevinw/pyflakes-vim.git",
# "http://github.com/tsaleh/vim-supertab.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"]
  # ["gist",          "12732", "plugin"],
  # ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
